### PR TITLE
Update template

### PR DESCRIPTION
**Pull request by srajiang**
This PR sees updates to the bolt js starter template which includes: 

1. Canonical "reverse string" function definition to `manifest.json`
2. "Reverse string" runtime code and `/functions` directory to listeners
3. A updated slack.json

Todos
1. Update bolt dependency in `package.json` to use Bolt JS beta release

### CODE REVIEW

**Review by filmaj — APPROVED** [review]
LGTM! May want to merge https://github.com/srajiang/bolt-js-starter-template/pull/2 in first though

**Review by misscoded — CHANGES_REQUESTED** [review]
👋🏼 This sample template is used for building 1.0 applications, so I have concerns about the dependency linking out to and using functionality available only on a beta branch. Can you two catch me up on what the end goal is?

**Comment by misscoded** [comment]
@srajiang I love the idea of a separate template for the time being. Once things are hardened and become available to all users, we can merge the two into a single template again. In the meantime, `-nextgen` or `-future` -- whatever language is being used most across the board and that you two like sounds good to me!

**Comment by srajiang** [comment]
I'm going to close this PR request! @misscoded An alternative to a whole separate template is just to have a branch off this template. If we are thinking about eventually merging, we could use `future` as the branch name.

**Pull request closed without merging**
